
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
# projects: []
# assignees: []
body:
  - type: dropdown
    attributes:
      label: 発生アプリ
      options:
        - webapp
        - extension
        - cdk(AWS)
        - それ以外
      default: 0
  - type: textarea
    attributes:
      label: 想定される挙動
      placeholder: 〜をクリックした場合、〜になる
  - type: textarea
    attributes:
      label: 現在の挙動
      placeholder: 〜をクリックした場合、〜になる
      description: ※可能であれば再現のキャプチャを添付してください
  - type: textarea
    attributes:
      label: 再現手順
      value: 1. 〜を開く
  - type: textarea
    attributes:
      label: 解決手段
  - type: textarea
    attributes:
      label: 備考
