
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
# projects: []
# assignees: []
body:
  - type: dropdown
    attributes:
      label: 発生アプリ
      options:
        - webapp
        - extension
        - cdk(AWS)
        - それ以外
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: 想定される挙動
      placeholder: 〜をクリックした場合、〜になる
    validations:
      required: true
  - type: textarea
    attributes:
      label: 現在の挙動
      placeholder: 〜をクリックした場合、〜になる
      description: ※可能であれば再現のキャプチャを添付してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
      value: 1. 〜を開く
    validations:
      required: false
  - type: textarea
    attributes:
      label: 解決手段
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 操作環境
      description: 再現した端末、ブラウザを選択してください
      options:
        - label: Mac
        - label: Windows
        - label: iPhone
        - label: Android
        - label: その他OS
        - label: safari
        - label: Chrome
        - label: その他ブラウザ
  - type: textarea
    attributes:
      label: 備考
